// Autogenerated from Pigeon (v26.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsBarcodeApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsBarcodeApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsBarcodeApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashBarcodeApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashBarcodeApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashBarcodeApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Enum representing different barcode types
enum BarcodeTypeEnum: Int {
  case aztec = 0
  case code128 = 1
  case code39 = 2
  case code39mod43 = 3
  case code93 = 4
  case codabar = 5
  case dataMatrix = 6
  case ean13 = 7
  case ean8 = 8
  case itf = 9
  case pdf417 = 10
  case qr = 11
  case upcA = 12
  case upcE = 13
  case interleaved = 14
}

/// Enum representing barcode value types (Android only)
enum BarcodeValueTypeEnum: Int {
  case unknown = 0
  case contactInfo = 1
  case email = 2
  case isbn = 3
  case phone = 4
  case product = 5
  case sms = 6
  case text = 7
  case url = 8
  case wifi = 9
  case geo = 10
  case calender = 11
  case license = 12
}

/// Enum representing camera resolutions
enum ResolutionEnum: Int {
  case sd480 = 0
  case hd720 = 1
  case hd1080 = 2
  case hd4k = 3
}

/// Enum representing camera framerates
enum FramerateEnum: Int {
  case fps30 = 0
  case fps60 = 1
  case fps120 = 2
  case fps240 = 3
}

/// Enum representing detection modes
enum DetectionModeEnum: Int {
  case pauseDetection = 0
  case pauseVideo = 1
  case continuous = 2
}

/// Enum representing camera positions
enum CameraPositionEnum: Int {
  case front = 0
  case back = 1
}

/// Enum representing iOS API modes
enum IOSApiModeEnum: Int {
  case avFoundation = 0
  case vision = 1
}

/// Represents a point with x and y coordinates
///
/// Generated class from Pigeon that represents data sent in messages.
struct PointData: Hashable {
  var x: Int64
  var y: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PointData? {
    let x = pigeonVar_list[0] as! Int64
    let y = pigeonVar_list[1] as! Int64

    return PointData(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
  static func == (lhs: PointData, rhs: PointData) -> Bool {
    return deepEqualsBarcodeApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBarcodeApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a detected barcode
///
/// Generated class from Pigeon that represents data sent in messages.
struct BarcodeData: Hashable {
  var type: BarcodeTypeEnum
  var value: String
  var valueType: BarcodeValueTypeEnum? = nil
  var cornerPoints: [PointData?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BarcodeData? {
    let type = pigeonVar_list[0] as! BarcodeTypeEnum
    let value = pigeonVar_list[1] as! String
    let valueType: BarcodeValueTypeEnum? = nilOrValue(pigeonVar_list[2])
    let cornerPoints: [PointData?]? = nilOrValue(pigeonVar_list[3])

    return BarcodeData(
      type: type,
      value: value,
      valueType: valueType,
      cornerPoints: cornerPoints
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      value,
      valueType,
      cornerPoints,
    ]
  }
  static func == (lhs: BarcodeData, rhs: BarcodeData) -> Bool {
    return deepEqualsBarcodeApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBarcodeApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for camera preview
///
/// Generated class from Pigeon that represents data sent in messages.
struct PreviewConfigurationData: Hashable {
  var textureId: Int64
  var targetRotation: Int64
  var height: Int64
  var width: Int64
  var analysisWidth: Int64
  var analysisHeight: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PreviewConfigurationData? {
    let textureId = pigeonVar_list[0] as! Int64
    let targetRotation = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64
    let width = pigeonVar_list[3] as! Int64
    let analysisWidth = pigeonVar_list[4] as! Int64
    let analysisHeight = pigeonVar_list[5] as! Int64

    return PreviewConfigurationData(
      textureId: textureId,
      targetRotation: targetRotation,
      height: height,
      width: width,
      analysisWidth: analysisWidth,
      analysisHeight: analysisHeight
    )
  }
  func toList() -> [Any?] {
    return [
      textureId,
      targetRotation,
      height,
      width,
      analysisWidth,
      analysisHeight,
    ]
  }
  static func == (lhs: PreviewConfigurationData, rhs: PreviewConfigurationData) -> Bool {
    return deepEqualsBarcodeApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBarcodeApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for initializing the scanner
///
/// Generated class from Pigeon that represents data sent in messages.
struct ScannerConfigurationData: Hashable {
  var types: [BarcodeTypeEnum?]
  var mode: DetectionModeEnum
  var resolution: ResolutionEnum
  var framerate: FramerateEnum
  var position: CameraPositionEnum
  var apiMode: IOSApiModeEnum? = nil
  var confidence: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScannerConfigurationData? {
    let types = pigeonVar_list[0] as! [BarcodeTypeEnum?]
    let mode = pigeonVar_list[1] as! DetectionModeEnum
    let resolution = pigeonVar_list[2] as! ResolutionEnum
    let framerate = pigeonVar_list[3] as! FramerateEnum
    let position = pigeonVar_list[4] as! CameraPositionEnum
    let apiMode: IOSApiModeEnum? = nilOrValue(pigeonVar_list[5])
    let confidence: Double? = nilOrValue(pigeonVar_list[6])

    return ScannerConfigurationData(
      types: types,
      mode: mode,
      resolution: resolution,
      framerate: framerate,
      position: position,
      apiMode: apiMode,
      confidence: confidence
    )
  }
  func toList() -> [Any?] {
    return [
      types,
      mode,
      resolution,
      framerate,
      position,
      apiMode,
      confidence,
    ]
  }
  static func == (lhs: ScannerConfigurationData, rhs: ScannerConfigurationData) -> Bool {
    return deepEqualsBarcodeApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBarcodeApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for updating scanner settings
///
/// Generated class from Pigeon that represents data sent in messages.
struct UpdateConfigurationData: Hashable {
  var types: [BarcodeTypeEnum?]? = nil
  var mode: DetectionModeEnum? = nil
  var resolution: ResolutionEnum? = nil
  var framerate: FramerateEnum? = nil
  var position: CameraPositionEnum? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UpdateConfigurationData? {
    let types: [BarcodeTypeEnum?]? = nilOrValue(pigeonVar_list[0])
    let mode: DetectionModeEnum? = nilOrValue(pigeonVar_list[1])
    let resolution: ResolutionEnum? = nilOrValue(pigeonVar_list[2])
    let framerate: FramerateEnum? = nilOrValue(pigeonVar_list[3])
    let position: CameraPositionEnum? = nilOrValue(pigeonVar_list[4])

    return UpdateConfigurationData(
      types: types,
      mode: mode,
      resolution: resolution,
      framerate: framerate,
      position: position
    )
  }
  func toList() -> [Any?] {
    return [
      types,
      mode,
      resolution,
      framerate,
      position,
    ]
  }
  static func == (lhs: UpdateConfigurationData, rhs: UpdateConfigurationData) -> Bool {
    return deepEqualsBarcodeApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBarcodeApi(value: toList(), hasher: &hasher)
  }
}

/// Data for image scanning
///
/// Generated class from Pigeon that represents data sent in messages.
struct ImageSourceData: Hashable {
  var imageBytes: FlutterStandardTypedData? = nil
  var rotation: Int64? = nil
  var useImagePicker: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImageSourceData? {
    let imageBytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[0])
    let rotation: Int64? = nilOrValue(pigeonVar_list[1])
    let useImagePicker = pigeonVar_list[2] as! Bool

    return ImageSourceData(
      imageBytes: imageBytes,
      rotation: rotation,
      useImagePicker: useImagePicker
    )
  }
  func toList() -> [Any?] {
    return [
      imageBytes,
      rotation,
      useImagePicker,
    ]
  }
  static func == (lhs: ImageSourceData, rhs: ImageSourceData) -> Bool {
    return deepEqualsBarcodeApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBarcodeApi(value: toList(), hasher: &hasher)
  }
}

private class BarcodeApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BarcodeTypeEnum(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BarcodeValueTypeEnum(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ResolutionEnum(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FramerateEnum(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DetectionModeEnum(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraPositionEnum(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return IOSApiModeEnum(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      return PointData.fromList(self.readValue() as! [Any?])
    case 137:
      return BarcodeData.fromList(self.readValue() as! [Any?])
    case 138:
      return PreviewConfigurationData.fromList(self.readValue() as! [Any?])
    case 139:
      return ScannerConfigurationData.fromList(self.readValue() as! [Any?])
    case 140:
      return UpdateConfigurationData.fromList(self.readValue() as! [Any?])
    case 141:
      return ImageSourceData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BarcodeApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BarcodeTypeEnum {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? BarcodeValueTypeEnum {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ResolutionEnum {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? FramerateEnum {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? DetectionModeEnum {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraPositionEnum {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? IOSApiModeEnum {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? PointData {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? BarcodeData {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? PreviewConfigurationData {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? ScannerConfigurationData {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? UpdateConfigurationData {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? ImageSourceData {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BarcodeApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BarcodeApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BarcodeApiPigeonCodecWriter(data: data)
  }
}

class BarcodeApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = BarcodeApiPigeonCodec(readerWriter: BarcodeApiPigeonCodecReaderWriter())
}


/// Host API for communication from Dart to native platforms
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FastBarcodeScannerHostApi {
  /// Initialize the camera and scanner with the given configuration
  func initialize(configuration: ScannerConfigurationData, completion: @escaping (Result<PreviewConfigurationData, Error>) -> Void)
  /// Start the camera
  func start(completion: @escaping (Result<Void, Error>) -> Void)
  /// Stop the camera
  func stop(completion: @escaping (Result<Void, Error>) -> Void)
  /// Start the barcode detector
  func startDetector(completion: @escaping (Result<Void, Error>) -> Void)
  /// Stop the barcode detector
  func stopDetector(completion: @escaping (Result<Void, Error>) -> Void)
  /// Dispose camera resources
  func dispose(completion: @escaping (Result<Void, Error>) -> Void)
  /// Toggle the camera torch/flash
  func toggleTorch(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Update scanner configuration
  func changeConfiguration(configuration: UpdateConfigurationData, completion: @escaping (Result<PreviewConfigurationData, Error>) -> Void)
  /// Scan barcode from image
  func scanImage(imageSource: ImageSourceData, completion: @escaping (Result<[BarcodeData?], Error>) -> Void)
  /// Retrieve cached image path for a barcode
  func retrieveCachedImage(code: String, completion: @escaping (Result<String?, Error>) -> Void)
  /// Clear all cached images
  func clearCachedImage(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FastBarcodeScannerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { BarcodeApiPigeonCodec.shared }
  /// Sets up an instance of `FastBarcodeScannerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FastBarcodeScannerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Initialize the camera and scanner with the given configuration
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationArg = args[0] as! ScannerConfigurationData
        api.initialize(configuration: configurationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Start the camera
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { _, reply in
        api.start { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    /// Stop the camera
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        api.stop { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    /// Start the barcode detector
    let startDetectorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.startDetector\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDetectorChannel.setMessageHandler { _, reply in
        api.startDetector { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startDetectorChannel.setMessageHandler(nil)
    }
    /// Stop the barcode detector
    let stopDetectorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.stopDetector\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopDetectorChannel.setMessageHandler { _, reply in
        api.stopDetector { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopDetectorChannel.setMessageHandler(nil)
    }
    /// Dispose camera resources
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        api.dispose { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    /// Toggle the camera torch/flash
    let toggleTorchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.toggleTorch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      toggleTorchChannel.setMessageHandler { _, reply in
        api.toggleTorch { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      toggleTorchChannel.setMessageHandler(nil)
    }
    /// Update scanner configuration
    let changeConfigurationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.changeConfiguration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      changeConfigurationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationArg = args[0] as! UpdateConfigurationData
        api.changeConfiguration(configuration: configurationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      changeConfigurationChannel.setMessageHandler(nil)
    }
    /// Scan barcode from image
    let scanImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.scanImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scanImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imageSourceArg = args[0] as! ImageSourceData
        api.scanImage(imageSource: imageSourceArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      scanImageChannel.setMessageHandler(nil)
    }
    /// Retrieve cached image path for a barcode
    let retrieveCachedImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.retrieveCachedImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      retrieveCachedImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let codeArg = args[0] as! String
        api.retrieveCachedImage(code: codeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      retrieveCachedImageChannel.setMessageHandler(nil)
    }
    /// Clear all cached images
    let clearCachedImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.clearCachedImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearCachedImageChannel.setMessageHandler { _, reply in
        api.clearCachedImage { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearCachedImageChannel.setMessageHandler(nil)
    }
  }
}
/// Flutter API for communication from native platforms to Dart
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FastBarcodeScannerFlutterApiProtocol {
  /// Called when barcodes are detected
  func onBarcodesDetected(barcodes barcodesArg: [BarcodeData?], completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when an error occurs
  func onError(errorCode errorCodeArg: String, errorMessage errorMessageArg: String, errorDetails errorDetailsArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class FastBarcodeScannerFlutterApi: FastBarcodeScannerFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: BarcodeApiPigeonCodec {
    return BarcodeApiPigeonCodec.shared
  }
  /// Called when barcodes are detected
  func onBarcodesDetected(barcodes barcodesArg: [BarcodeData?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerFlutterApi.onBarcodesDetected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([barcodesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when an error occurs
  func onError(errorCode errorCodeArg: String, errorMessage errorMessageArg: String, errorDetails errorDetailsArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorCodeArg, errorMessageArg, errorDetailsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
