name: fast_barcode_scanner_example
description: Demonstrates how to use the fast_barcode_scanner plugin.
publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: ">=3.32.0"

dependency_overrides:
  fast_barcode_scanner_platform_interface:
    path: ../../fast_barcode_scanner_platform_interface

dependencies:
  flutter:
    sdk: flutter

  fast_barcode_scanner:
    path: ../

  fast_barcode_scanner_platform_interface:
    path: ../../fast_barcode_scanner_platform_interface

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/