// Autogenerated from Pigeon (v26.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.jhoogstraat.fast_barcode_scanner.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object BarcodeApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Enum representing different barcode types */
enum class BarcodeType(val raw: Int) {
  AZTEC(0),
  CODE128(1),
  CODE39(2),
  CODE39MOD43(3),
  CODE93(4),
  CODABAR(5),
  DATA_MATRIX(6),
  EAN13(7),
  EAN8(8),
  ITF(9),
  PDF417(10),
  QR(11),
  UPC_A(12),
  UPC_E(13),
  INTERLEAVED(14);

  companion object {
    fun ofRaw(raw: Int): BarcodeType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Enum representing barcode value types (Android only) */
enum class BarcodeValueType(val raw: Int) {
  UNKNOWN(0),
  CONTACT_INFO(1),
  EMAIL(2),
  ISBN(3),
  PHONE(4),
  PRODUCT(5),
  SMS(6),
  TEXT(7),
  URL(8),
  WIFI(9),
  GEO(10),
  CALENDER(11),
  LICENSE(12);

  companion object {
    fun ofRaw(raw: Int): BarcodeValueType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Enum representing camera resolutions */
enum class Resolution(val raw: Int) {
  SD480(0),
  HD720(1),
  HD1080(2),
  HD4K(3);

  companion object {
    fun ofRaw(raw: Int): Resolution? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Enum representing camera framerates */
enum class Framerate(val raw: Int) {
  FPS30(0),
  FPS60(1),
  FPS120(2),
  FPS240(3);

  companion object {
    fun ofRaw(raw: Int): Framerate? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Enum representing detection modes */
enum class DetectionMode(val raw: Int) {
  PAUSE_DETECTION(0),
  PAUSE_VIDEO(1),
  CONTINUOUS(2);

  companion object {
    fun ofRaw(raw: Int): DetectionMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Enum representing camera positions */
enum class CameraPosition(val raw: Int) {
  FRONT(0),
  BACK(1);

  companion object {
    fun ofRaw(raw: Int): CameraPosition? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Enum representing iOS API modes */
enum class IOSApiMode(val raw: Int) {
  AV_FOUNDATION(0),
  VISION(1);

  companion object {
    fun ofRaw(raw: Int): IOSApiMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Represents a point with x and y coordinates
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PointData (
  val x: Long,
  val y: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PointData {
      val x = pigeonVar_list[0] as Long
      val y = pigeonVar_list[1] as Long
      return PointData(x, y)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PointData) {
      return false
    }
    if (this === other) {
      return true
    }
    return BarcodeApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Represents a detected barcode
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BarcodeData (
  val type: BarcodeType,
  val value: String,
  val valueType: BarcodeValueType? = null,
  val cornerPoints: List<PointData?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BarcodeData {
      val type = pigeonVar_list[0] as BarcodeType
      val value = pigeonVar_list[1] as String
      val valueType = pigeonVar_list[2] as BarcodeValueType?
      val cornerPoints = pigeonVar_list[3] as List<PointData?>?
      return BarcodeData(type, value, valueType, cornerPoints)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      value,
      valueType,
      cornerPoints,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BarcodeData) {
      return false
    }
    if (this === other) {
      return true
    }
    return BarcodeApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for camera preview
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PreviewConfiguration (
  val textureId: Long,
  val targetRotation: Long,
  val height: Double,
  val width: Double,
  val analysisWidth: Double,
  val analysisHeight: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PreviewConfiguration {
      val textureId = pigeonVar_list[0] as Long
      val targetRotation = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Double
      val width = pigeonVar_list[3] as Double
      val analysisWidth = pigeonVar_list[4] as Double
      val analysisHeight = pigeonVar_list[5] as Double
      return PreviewConfiguration(textureId, targetRotation, height, width, analysisWidth, analysisHeight)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      textureId,
      targetRotation,
      height,
      width,
      analysisWidth,
      analysisHeight,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PreviewConfiguration) {
      return false
    }
    if (this === other) {
      return true
    }
    return BarcodeApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for initializing the scanner
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ScannerConfiguration (
  val types: List<BarcodeType?>,
  val mode: DetectionMode,
  val resolution: Resolution,
  val framerate: Framerate,
  val position: CameraPosition,
  val apiMode: IOSApiMode? = null,
  val confidence: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScannerConfiguration {
      val types = pigeonVar_list[0] as List<BarcodeType?>
      val mode = pigeonVar_list[1] as DetectionMode
      val resolution = pigeonVar_list[2] as Resolution
      val framerate = pigeonVar_list[3] as Framerate
      val position = pigeonVar_list[4] as CameraPosition
      val apiMode = pigeonVar_list[5] as IOSApiMode?
      val confidence = pigeonVar_list[6] as Double?
      return ScannerConfiguration(types, mode, resolution, framerate, position, apiMode, confidence)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      types,
      mode,
      resolution,
      framerate,
      position,
      apiMode,
      confidence,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ScannerConfiguration) {
      return false
    }
    if (this === other) {
      return true
    }
    return BarcodeApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for updating scanner settings
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class UpdateConfiguration (
  val types: List<BarcodeType?>? = null,
  val mode: DetectionMode? = null,
  val resolution: Resolution? = null,
  val framerate: Framerate? = null,
  val position: CameraPosition? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UpdateConfiguration {
      val types = pigeonVar_list[0] as List<BarcodeType?>?
      val mode = pigeonVar_list[1] as DetectionMode?
      val resolution = pigeonVar_list[2] as Resolution?
      val framerate = pigeonVar_list[3] as Framerate?
      val position = pigeonVar_list[4] as CameraPosition?
      return UpdateConfiguration(types, mode, resolution, framerate, position)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      types,
      mode,
      resolution,
      framerate,
      position,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is UpdateConfiguration) {
      return false
    }
    if (this === other) {
      return true
    }
    return BarcodeApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Data for image scanning
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ImageSourceData (
  val imageBytes: ByteArray? = null,
  val rotation: Long? = null,
  val useImagePicker: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ImageSourceData {
      val imageBytes = pigeonVar_list[0] as ByteArray?
      val rotation = pigeonVar_list[1] as Long?
      val useImagePicker = pigeonVar_list[2] as Boolean
      return ImageSourceData(imageBytes, rotation, useImagePicker)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      imageBytes,
      rotation,
      useImagePicker,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ImageSourceData) {
      return false
    }
    if (this === other) {
      return true
    }
    return BarcodeApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class BarcodeApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BarcodeType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BarcodeValueType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          Resolution.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          Framerate.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DetectionMode.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CameraPosition.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          IOSApiMode.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PointData.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BarcodeData.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PreviewConfiguration.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScannerConfiguration.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UpdateConfiguration.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ImageSourceData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BarcodeType -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is BarcodeValueType -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is Resolution -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is Framerate -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is DetectionMode -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is CameraPosition -> {
        stream.write(134)
        writeValue(stream, value.raw)
      }
      is IOSApiMode -> {
        stream.write(135)
        writeValue(stream, value.raw)
      }
      is PointData -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is BarcodeData -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is PreviewConfiguration -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is ScannerConfiguration -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is UpdateConfiguration -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is ImageSourceData -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API for communication from Dart to native platforms
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface FastBarcodeScannerHostApi {
  /** Initialize the camera and scanner with the given configuration */
  fun initialize(configuration: ScannerConfiguration, callback: (Result<PreviewConfiguration>) -> Unit)
  /** Start the camera */
  fun start(callback: (Result<Unit>) -> Unit)
  /** Stop the camera */
  fun stop(callback: (Result<Unit>) -> Unit)
  /** Start the barcode detector */
  fun startDetector(callback: (Result<Unit>) -> Unit)
  /** Stop the barcode detector */
  fun stopDetector(callback: (Result<Unit>) -> Unit)
  /** Dispose camera resources */
  fun dispose(callback: (Result<Unit>) -> Unit)
  /** Toggle the camera torch/flash */
  fun toggleTorch(callback: (Result<Boolean>) -> Unit)
  /** Update scanner configuration */
  fun changeConfiguration(configuration: UpdateConfiguration, callback: (Result<PreviewConfiguration>) -> Unit)
  /** Scan barcode from image */
  fun scanImage(imageSource: ImageSourceData, callback: (Result<List<BarcodeData?>>) -> Unit)
  /** Retrieve cached image path for a barcode */
  fun retrieveCachedImage(code: String, callback: (Result<String?>) -> Unit)
  /** Clear all cached images */
  fun clearCachedImage(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by FastBarcodeScannerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      BarcodeApiPigeonCodec()
    }
    /** Sets up an instance of `FastBarcodeScannerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FastBarcodeScannerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationArg = args[0] as ScannerConfiguration
            api.initialize(configurationArg) { result: Result<PreviewConfiguration> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BarcodeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BarcodeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.start{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BarcodeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BarcodeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stop{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BarcodeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BarcodeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.startDetector$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startDetector{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BarcodeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BarcodeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.stopDetector$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopDetector{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BarcodeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BarcodeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.dispose{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BarcodeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BarcodeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.toggleTorch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.toggleTorch{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BarcodeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BarcodeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.changeConfiguration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationArg = args[0] as UpdateConfiguration
            api.changeConfiguration(configurationArg) { result: Result<PreviewConfiguration> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BarcodeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BarcodeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.scanImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val imageSourceArg = args[0] as ImageSourceData
            api.scanImage(imageSourceArg) { result: Result<List<BarcodeData?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BarcodeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BarcodeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.retrieveCachedImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val codeArg = args[0] as String
            api.retrieveCachedImage(codeArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BarcodeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BarcodeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerHostApi.clearCachedImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearCachedImage{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BarcodeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BarcodeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter API for communication from native platforms to Dart
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class FastBarcodeScannerFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by FastBarcodeScannerFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      BarcodeApiPigeonCodec()
    }
  }
  /** Called when barcodes are detected */
  fun onBarcodesDetected(barcodesArg: List<BarcodeData?>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerFlutterApi.onBarcodesDetected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(barcodesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BarcodeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when an error occurs */
  fun onError(errorCodeArg: String, errorMessageArg: String, errorDetailsArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.fast_barcode_scanner_platform_interface.FastBarcodeScannerFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(errorCodeArg, errorMessageArg, errorDetailsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BarcodeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
